<?xml version="1.0"?>

<robot name = "pupper" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name = "full_urdf" value = "true"/>

    <xacro:if value = "${full_urdf}">
    <xacro:include filename = "$(find workstation)/pupper_description/colors.xacro"/>
    </xacro:if>

    <xacro:include filename = "$(find workstation)/pupper_description/motor.xacro"/>
    <xacro:include filename = "$(find workstation)/pupper_description/left_leg.xacro"/>
    <xacro:include filename = "$(find workstation)/pupper_description/right_leg.xacro"/>

    <xacro:property name = "PI"            value = "3.14159265359"/>
    <xacro:property name = "VisualPath"    value = "package://workstation/pupper_description/Pupper_STL"/>
    <xacro:property name = "CollisionPath" value = "package://workstation/pupper_description/Pupper_STL"/>

    <!-- Conversions -->
    <xacro:property name = "meshScale_mm"  value = "0.001 0.001 0.001"/>
    <xacro:property name = "meshScale_in"  value = "0.0254 0.0254 0.0254"/>
    <xacro:property name = "meshScale_meters"  value = "1.0 1.0 1.0"/>
    <xacro:property name = "mm2m"  value = "0.001"/>

    <!-- Convert inertia from g*mm^2 to kg*m^2 -->
    <xacro:macro name = "scaleMMOI" params = "ixx iyy izz ixy ixz iyz">
        <xacro:property name = "kConvert" value = "${1e-9}"/>
        <inertia ixx = "${ixx*kConvert}" iyy = "${iyy*kConvert}" izz = "${izz*kConvert}"
                 ixy = "${ixy*kConvert}" iyz = "${iyz*kConvert}" ixz = "${ixz*kConvert}"/>
    </xacro:macro>

    <!-- Convert grams to kilograms -->
    <xacro:macro name = "scaleMass" params = "mass">
        <mass value = "${mass * 0.001}"/>
    </xacro:macro>

    <!-- Convert origin in mm to m-->
    <xacro:macro name = "scaleOrigin" params = "x y z">
        <origin xyz = "${x * mm2m} ${y * mm2m} ${z * mm2m}" rpy = "0 0 0"/>
    </xacro:macro>

    <!-- +++++++++++++++++++++++++++++++ -->
    <!-- MEASURED / ESTIMATED PROPERTIES -->
    <!-- +++++++++++++++++++++++++++++++ -->
    <!-- Estimated rotor inertia - note Gazebo will unfortunately propagate the inertia to the parent links 
         but its the closest we can get to modeling the reflected inertia of the gear box/ rotor-->
    <xacro:property name = "rotor_inertia" value = "${0.0028 * 1e9}"/> <!-- (g*mm^2) -->

    <!-- +++++++++++++++++++++++++++++++ -->
    <!-- MASS PROPERTIES FROM SOLIDWORKS -->
    <!-- +++++++++++++++++++++++++++++++ -->

    <!-- Bottom PCB -->
    <xacro:property name = "bottom_PCB_mass" value = "1086.5"/> <!-- (g) (lumped with all fixed bodies) -->

    <xacro:property name = "bottom_PCB_com_x" value = "-16.46"/> <!-- (mm) -->
    <xacro:property name = "bottom_PCB_com_y" value = "0"/> 
    <xacro:property name = "bottom_PCB_com_z" value = "37.53"/> 

    <xacro:property name = "bottom_PCB_ixx" value = "1919398.64"/> <!-- (g*mm^2) -->
    <xacro:property name = "bottom_PCB_iyy" value = "8759021.12"/>
    <xacro:property name = "bottom_PCB_izz" value = "9498546.46"/>
    <xacro:property name = "bottom_PCB_ixy" value = "235.71"/>
    <xacro:property name = "bottom_PCB_ixz" value = "1884.89"/>
    <xacro:property name = "bottom_PCB_iyz" value = "10.99"/>


    <!-- Left Hub -->
    <xacro:property name = "left_hub_mass" value = "109.8"/> <!-- (g) -->

    <xacro:property name = "left_hub_com_x" value = "-29"/> <!-- (mm) -->
    <xacro:property name = "left_hub_com_y" value = "0.31"/> 
    <xacro:property name = "left_hub_com_z" value = "0"/>

    <xacro:property name = "left_hub_ixx" value = "${23576.71 + rotor_inertia}"/> <!-- (g*mm^2) -->
    <xacro:property name = "left_hub_iyy" value = "12321.79"/>
    <xacro:property name = "left_hub_izz" value = "27265.99"/>
    <xacro:property name = "left_hub_ixy" value = "-34.26"/>
    <xacro:property name = "left_hub_ixz" value = "-0.01"/>
    <xacro:property name = "left_hub_iyz" value = "0.01"/>


    <!-- Right Hub -->
    <xacro:property name = "right_hub_mass" value = "109.8"/> <!-- (g) -->

    <xacro:property name = "right_hub_com_x" value = "-29"/> <!-- (mm) -->
    <xacro:property name = "right_hub_com_y" value = "-0.31"/> 
    <xacro:property name = "right_hub_com_z" value = "0"/>

    <xacro:property name = "right_hub_ixx" value = "${23576.71  + rotor_inertia}"/> <!-- (g*mm^2) -->
    <xacro:property name = "right_hub_iyy" value = "12321.79"/>
    <xacro:property name = "right_hub_izz" value = "27265.99"/>
    <xacro:property name = "right_hub_ixy" value = "-34.26"/>
    <xacro:property name = "right_hub_ixz" value = "-0.01"/>
    <xacro:property name = "right_hub_iyz" value = "-0.02"/>


    <!-- Left Upper Link -->
    <xacro:property name = "left_upper_link_mass" value = "143.55"/> <!-- (g) -->

    <xacro:property name = "left_upper_link_com_x" value = "0"/> <!-- (mm) -->
    <xacro:property name = "left_upper_link_com_y" value = "36.76"/> 
    <xacro:property name = "left_upper_link_com_z" value = "-59.83"/>

    <xacro:property name = "left_upper_link_ixx" value = "171730.23"/> <!-- (g*mm^2) -->
    <xacro:property name = "left_upper_link_iyy" value = "141191.83"/>
    <xacro:property name = "left_upper_link_izz" value = "43033.83"/>
    <xacro:property name = "left_upper_link_ixy" value = "0.01"/>
    <xacro:property name = "left_upper_link_ixz" value = "-0.06"/>
    <xacro:property name = "left_upper_link_iyz" value = "45763.54"/>


    <!-- Right Upper Link -->
    <xacro:property name = "right_upper_link_mass" value = "143.55"/> <!-- (g) -->

    <xacro:property name = "right_upper_link_com_x" value = "0"/> <!-- (mm) -->
    <xacro:property name = "right_upper_link_com_y" value = "-36.76"/> 
    <xacro:property name = "right_upper_link_com_z" value = "-59.83"/>

    <xacro:property name = "right_upper_link_ixx" value = "171730.23"/> <!-- (g*mm^2) -->
    <xacro:property name = "right_upper_link_iyy" value = "141191.83"/>
    <xacro:property name = "right_upper_link_izz" value = "43033.83"/>
    <xacro:property name = "right_upper_link_ixy" value = "0.01"/>
    <xacro:property name = "right_upper_link_ixz" value = "0.06"/>
    <xacro:property name = "right_upper_link_iyz" value = "-45763.54"/>


    <!-- Left Lower Link -->
    <xacro:property name = "left_lower_link_mass" value = "21.00"/> <!-- (g) -->

    <xacro:property name = "left_lower_link_com_x" value = "-0.22"/> <!-- (mm) -->
    <xacro:property name = "left_lower_link_com_y" value = "-12.19"/> 
    <xacro:property name = "left_lower_link_com_z" value = "-33.35"/>
    
    <xacro:property name = "left_lower_link_ixx" value = "43753.77"/> <!-- (g*mm^2) -->
    <xacro:property name = "left_lower_link_iyy" value = "${44138.15  + rotor_inertia}"/>
    <xacro:property name = "left_lower_link_izz" value = "856.89"/>
    <xacro:property name = "left_lower_link_ixy" value = "12.76"/>
    <xacro:property name = "left_lower_link_ixz" value = "-359.76"/>
    <xacro:property name = "left_lower_link_iyz" value = "456.47"/>


    <!-- Right Lower Link -->
    <xacro:property name = "right_lower_link_mass" value = "21.00"/> <!-- (g) -->

    <xacro:property name = "right_lower_link_com_x" value = "-0.22"/> <!-- (mm) -->
    <xacro:property name = "right_lower_link_com_y" value = "12.19"/> 
    <xacro:property name = "right_lower_link_com_z" value = "-33.35"/>

    <xacro:property name = "right_lower_link_ixx" value = "43753.05"/> <!-- (g*mm^2) -->
    <xacro:property name = "right_lower_link_iyy" value = "${44137.54  + rotor_inertia}"/>
    <xacro:property name = "right_lower_link_izz" value = "856.82"/>
    <xacro:property name = "right_lower_link_ixy" value = "-12.74"/>
    <xacro:property name = "right_lower_link_ixz" value = "-360.13"/>
    <xacro:property name = "right_lower_link_iyz" value = "-455.13"/>

    <!-- Battery mass -->
    <!-- <xacro:property name = "battery_mass" value = "0.205"/> -->
    <!-- Battery location in x of bottom_PCB frame (m)-->
    <!-- <xacro:property name = "batt_loc_x" value = "-0.028"/> -->

    <!-- ++++++++++++++++++++++++++++++++++++ -->
    <!-- KINEMATIC PROPERTIES FROM SOLIDWORKS -->
    <!-- ++++++++++++++++++++++++++++++++++++ -->

    <xacro:property name="back_left_hub_relative_origin">
        <xacro:scaleOrigin x = "-122.00" y = "47" z = "43.5"/>
    </xacro:property>
    <!-- Other origins hard coded ... -->

    <!-- +++++++++++++++++++ -->
    <!-- SIMULATION SETTINGS -->
    <!-- +++++++++++++++++++ -->

    <xacro:property name = "contact_kp">
        <kp>1e6</kp> 
    </xacro:property>
    <xacro:property name = "contact_kd">
        <kd>1</kd>
    </xacro:property>
    <xacro:property name = "joint_friction">
        <dynamics damping = "0.001" friction = "0.17"/>
    </xacro:property>
    <!-- Connect the plugin -->
    <gazebo>
        <plugin filename = "libpupper_plugin.so" name = "pupper_plugin"/>
    </gazebo>

    <!-- ++++++++++++++++ -->
    <!-- ROBOT START HERE -->
    <!-- ++++++++++++++++ -->

    <!-- Base link of the robot -->
    <link name = "bottom_PCB">
        <inertial>
            <xacro:scaleOrigin  x = "${bottom_PCB_com_x}" 
                                y = "${bottom_PCB_com_y}" 
                                z = "${bottom_PCB_com_z}"/>
            <xacro:scaleMass mass = "${bottom_PCB_mass}"/>
            <xacro:scaleMMOI ixx  = "${bottom_PCB_ixx}"
                             iyy  = "${bottom_PCB_iyy}"
                             izz  = "${bottom_PCB_izz}"
                             ixy  = "${bottom_PCB_ixy}"
                             ixz  = "${bottom_PCB_ixz}"
                             iyz  = "${bottom_PCB_iyz}" />
        </inertial>

        <xacro:if value = "${full_urdf}">
        <visual name = "bottom_PCB_visual">
            <geometry>
                <mesh filename = "${VisualPath}/Body/assembly_body_STL.stl" scale = "${meshScale_meters}"/>
            </geometry>
        </visual>

        <collision name = "bottom_PCB_collision">
            <origin xyz = "0.0 0.0 0.04355" rpy = "0 0 0"/>
            <geometry>
                <box size = "0.264 0.124 0.0901"/>
            </geometry>
            <!-- <geometry>
                <mesh filename = "${CollisionPath}/Body/assembly_body_simplified.dae" scale = "${meshScale_meters}"/>
            </geometry> -->
        </collision>
        </xacro:if>
    </link>

    <!-- Connect battery to bottom PCB -->
    <!-- 
    <joint name = "battery_to_body" type = "fixed">
        <parent link = "bottom_PCB"/>
        <child  link = "battery"/>
        <origin xyz = "${batt_loc_x} 0.00 ${batt_z/2}" rpy = "0 0 ${PI/2}"/>
    </joint>
    -->

    <!-- back left leg -->
    <xacro:leftLeg name = "back" parent = "bottom_PCB">
        <!-- <origin xyz = "-0.122 0.047 0.0435" rpy = "0 0 0"/> -->
        <xacro:insert_block name = "back_left_hub_relative_origin"/>
        <origin xyz = "-0.0315 0.0215 0" rpy = "0 0 0"/> 
        <origin xyz = "0 0.023 -0.080" rpy = "0 0 0"/>
    </xacro:leftLeg>

    <!-- back right leg-->
    <xacro:rightLeg name = "back" parent = "bottom_PCB">
        <origin xyz = "-0.122 -0.047 0.0435" rpy = "0 0 0"/>
        <origin xyz = "-0.0315 -0.0215 0" rpy = "0 0 0"/>
        <origin xyz = "0 -0.023 -0.080" rpy = "0 0 0"/>
    </xacro:rightLeg>

    <!-- front left leg -->
    <xacro:leftLeg name = "front" parent = "bottom_PCB">
        <origin xyz = "0.078 0.047 0.0435" rpy = "0 0 0"/>
        <origin xyz = "-0.0315 0.0215 0" rpy = "0 0 0"/>
        <origin xyz = "0 0.023 -0.080" rpy = "0 0 0"/>
    </xacro:leftLeg>

    <!-- front right leg -->
    <xacro:rightLeg name = "front" parent = "bottom_PCB">
        <origin xyz = "0.078 -0.047 0.0435" rpy = "0 0 0"/>
        <origin xyz = "-0.0315 -0.0215 0" rpy = "0 0 0"/>
        <origin xyz = "0 -0.023 -0.080" rpy = "0 0 0"/>
    </xacro:rightLeg>

</robot>