#!/bin/bash
#This is a bash script to build the code and run the Gazebo simulation

cd ~/WBC_catkin_ws/src/PupperWholeBodyControl/workstation/plugins/build
#catkin build # builds a catkin package containing all cpp except gazebo plugins 
catkin build -DCMAKE_BUILD_TYPE=Release # Release mode
#catkin build -DCMAKE_BUILD_TYPE=Debug # Debug mode
cmake ..
make -j 

roslaunch workstation load_pupper.launch
